version: '3'

services:
  graph:
    image: tinkerpop/gremlin-server:3.4
    user: "1000"
    volumes:
      - ./node_modules/@jupiterone/jupiter-managed-integration-sdk/gremlin-client/conf:/etc/opt
    restart: unless-stopped
    command: /etc/opt/gremlin-server.yaml
    ports:
      - "8182:8182"
